// <auto-generated />
namespace PartyProductsMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddedVirtualKeyWordNavigationPropertyInPartyProduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedVirtualKeyWordNavigationPropertyInPartyProduct));
        
        string IMigrationMetadata.Id
        {
            get { return "202311221006434_Added-VirtualKeyWord-NavigationProperty-In-Party-Product"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
