// <auto-generated />
namespace PartyProductsMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddPartyColumnInInvoiceDetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPartyColumnInInvoiceDetails));
        
        string IMigrationMetadata.Id
        {
            get { return "202311221158415_Add-PartyColumn-In-InvoiceDetails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
